SITE_NAME: "binhdanhocvuso.hnue.edu.vn"
BOOK_URL: ""
LOG_DIR: "/openedx/data/logs"
LOGGING_ENV: "sandbox"
OAUTH_OIDC_ISSUER: "https://binhdanhocvuso.hnue.edu.vn/oauth2"
PLATFORM_NAME: "Bình dân học vụ số - HNUE"
FEATURES:
  
  
  CERTIFICATES_HTML_VIEW: true
  PREVIEW_LMS_BASE: "preview.binhdanhocvuso.hnue.edu.vn"
  ENABLE_CSMH_EXTENDED: false
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
  ENABLE_GRADE_DOWNLOADS: true
  ENABLE_LEARNER_RECORDS: false
  ENABLE_MOBILE_REST_API: true
  ENABLE_OAUTH2_PROVIDER: true
  ENABLE_PREREQUISITE_COURSES: true
  ENABLE_THIRD_PARTY_AUTH: true
  MILESTONES_APP: true
LMS_ROOT_URL: "https://binhdanhocvuso.hnue.edu.vn"
CMS_ROOT_URL: "https://studio.binhdanhocvuso.hnue.edu.vn"
CMS_BASE: "studio.binhdanhocvuso.hnue.edu.vn"
LMS_BASE: "binhdanhocvuso.hnue.edu.vn"
CONTACT_EMAIL: "support@hnue.edu.vn"
CELERY_BROKER_TRANSPORT: "redis"
CELERY_BROKER_HOSTNAME: "redis:6379"
CELERY_BROKER_VHOST: "0"
CELERY_BROKER_USER: ""
CELERY_BROKER_PASSWORD: ""
ALTERNATE_WORKER_QUEUES: "cms"
ENABLE_COMPREHENSIVE_THEMING: true
EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST: "smtp.gmail.com"
EMAIL_PORT: 587
EMAIL_USE_TLS: true
ACE_ROUTING_KEY: "edx.lms.core.default"
HTTPS: "on"
LANGUAGE_CODE: "vi"
SESSION_COOKIE_DOMAIN: "binhdanhocvuso.hnue.edu.vn"

SECRET_KEY: "1Pq03tl8MqAS3bOUBAdlgApM"
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
DOC_STORE_CONFIG: null
XQUEUE_INTERFACE:
  django_auth: null
  url: null
DATABASES:
  default:
    ENGINE: "django.db.backends.mysql"
    HOST: "mysql"
    PORT: 3306
    NAME: "openedx"
    USER: "openedx"
    PASSWORD: "QMSLie9T"
    ATOMIC_REQUESTS: true
    OPTIONS:
      init_command: "SET sql_mode='STRICT_TRANS_TABLES'"
      charset: "utf8mb4"
EMAIL_HOST_USER: "no-replylms@hnue.edu.vn"
EMAIL_HOST_PASSWORD: "opzwlxolfyopcxpd"
